table 'Dim Attribute'
	lineageTag: d1c10dc2-1d56-48cd-b677-336d755c1ce3

	column Attribute
		dataType: string
		lineageTag: fd399b72-a748-4332-a046-78872d4a551f
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Attribute ID'
		dataType: int64
		formatString: 0
		lineageTag: 685b2927-a10d-45d1-8a97-67aeebbf3986
		summarizeBy: none
		sourceColumn: Attribute ID

		annotation SummarizationSetBy = Automatic

	partition 'Dim Attribute' = m
		mode: import
		queryGroup: 'Dimension Tables'
		source =
				let
				    Source = #"Sustainability Scorecard data",
				    #"Imported Excel Workbook" = Excel.Workbook(Source),
				    #"Dim Attribute_Sheet" = #"Imported Excel Workbook"{[Item="Dim Attribute",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Dim Attribute_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Attribute", type text}, {"Attribute ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

