table 'Fact Projects Table'
	lineageTag: 1133ed2b-34bb-429c-b219-4a4b6b855ffd

	measure 'Project ID' =
			
			SELECTEDVALUE('Fact Projects Table'[Project])
		lineageTag: 062632e1-c78c-45ed-980d-e2e0f693e171

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 6c83e528-8a28-4db2-8906-f3935157df2e
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: b5011d0e-1c9e-43cf-a24f-0a3fee425ba2
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: 7e3cfef5-f780-4338-84ed-14eef49f60ba
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: ed5f5152-6164-40bb-9699-d8560f56a327
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 7afc0178-59a1-4a9a-9468-cbc091173b60
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		formatString: #,0
		lineageTag: 7ca3754a-e660-4ee2-9e77-86b3cea9d2f4
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'KPI ID'
		dataType: int64
		formatString: 0
		lineageTag: 6ae1002c-07a0-46c2-907e-a8c11c438f05
		summarizeBy: none
		sourceColumn: KPI ID

		annotation SummarizationSetBy = Automatic

	column 'Topic ID'
		dataType: int64
		formatString: 0
		lineageTag: 96f6443d-a271-4db9-84bd-7b2bc4613214
		summarizeBy: none
		sourceColumn: Topic ID

		annotation SummarizationSetBy = Automatic

	column 'Activity Name'
		dataType: string
		lineageTag: 5a1a0995-9063-4e09-bf46-06b2c71b5d55
		summarizeBy: none
		sourceColumn: Activity Name

		annotation SummarizationSetBy = Automatic

	column 'Project Name' = COMBINEVALUES(" ", 'Fact Projects Table'[Project], 'Fact Projects Table'[Activity Name])
		lineageTag: 0db7664d-9b5c-4a70-b35f-2c66a48f3a80
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Derived end-of-quarter date from Year and Quarter integer columns
	column 'End of Quarter Date' = EOMONTH(DATE('Fact Projects Table'[Year], 'Fact Projects Table'[Quarter] * 3, 1), 0)
		dataType: dateTime
		lineageTag: 5d4e1902-f02f-4ebc-b69f-dca877185162

	column 'OE name'
		dataType: string
		lineageTag: 8185f6c0-a351-4caf-92b0-3c98e924c5b0
		summarizeBy: none
		sourceColumn: OE name

		annotation SummarizationSetBy = Automatic

	column Segment = "Petcare"
		lineageTag: 6cb6e4bf-b943-427d-a3f4-b98c4aef3290
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Fact Projects Table' = m
		mode: import
		queryGroup: 'Fact Tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Year = _t, Quarter = _t, Division = _t, OE name= _t, Project = _t, Attribute = _t, Value = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Year", Int64.Type}, {"Quarter", Int64.Type}, {"Division", type text}, {"OE name", type text}, {"Project", type text}, {"Attribute", type text}, {"Value", type number}}),
				    #"Appended Query" = Table.Combine({#"Changed Type", #"CAP Projects GHG Actuals", #"CAP Projects GHG Planned", #"CAP Projects GHG Investment", #"CAP Projects GHG Replan"})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

