createOrReplace

	ref table Measures_table

		measure 'Current Quarter New' = ```
				
				/*Scorecard Current Values obtained from the KPI Dynamic Measure. YEE% of Target Delivered is calculated separately as this is derived from two other KPIs (YEE and Targets) */ 
				VAR KPIName = SELECTEDVALUE('Dynamic KPI List'[KPI Name ])
				VAR ReportType = SELECTEDVALUE('Dynamic Report Type'[Report Type])
				VAR KPI_Value = 
				    CALCULATE(
				        [KPI Dynamic Measure New], 
				        'KPI Intelligence'[Time Period Calculations] = "Current Quarter"
				    )
				
				VAR YEE_Percent = 
				    CALCULATE(
				        [YEE% of Target Delivered New], 
				        'KPI Intelligence'[Time Period Calculations] = "Current Quarter"
				    )
				
				RETURN
				    SWITCH(
				        ReportType,
				        "YEE % of Target Delivered",
				            //BLANK(),
				            IF(
				                OR(CONTAINSSTRING(KPIName, "%"), [NoCalcList New]), 
				                //CONTAINSSTRING(KPIName, "%"), 
				                BLANK(),
				                YEE_Percent
				            ),
				        "YTD Active Projects",
				            IF(
				                OR(CONTAINSSTRING(KPIName, "%"), [NoCalcList New]),
				                BLANK(),
				                KPI_Value
				            ),
				        "Targets",
				            IF(
				                //OR(CONTAINSSTRING(KPIName, "%"), [NoCalcList]),
				                CONTAINSSTRING(KPIName, "%"),
				                BLANK(),
				                KPI_Value
				            ),
				        KPI_Value
				    )
				```
			displayFolder: Scorecard Digital
			lineageTag: 1a436dc2-16f0-4fca-8565-9b7aa9483fe5

			formatStringDefinition = ```
					VAR FormatString = SELECTEDVALUE('Dim KPI'[Data Format])
					VAR CurrentValue = ABS(IF(SELECTEDMEASURE()= "-", BLANK(), SELECTEDMEASURE()))
					VAR ReportType = SELECTEDVALUE('Dynamic Report Type'[Report Type])
					VAR KPIName = SELECTEDVALUE('Dim KPI'[KPI Name])
					RETURN
					
					
					IF(ReportType IN {"Replan", "Investment YEE"}, 
					SWITCH (
					        TRUE (),
					        // Special cases to force K and M in the sample report
					        CurrentValue <= 1E3, "$#,0.0",
					        CurrentValue <= 1E6, "$#,0,.0 K",
					        CurrentValue <= 1E9, "$#,0,,.0 M",
					        CurrentValue <= 1E12, "$#,0,,,.0 B"
					    ),
					
					//IF(ReportType = "YEE % of Target Delivered" && CONTAINSSTRING(KPIName, "%"), BLANK(),
					IF(ReportType = "YEE % of Target Delivered", "#,0.0%",
					
					IF(ReportType IN {"YTD Active Projects", "Total Planned Activities"},
					SWITCH (
					        TRUE (),
					        // Special cases to force K and M in the sample report
					        CurrentValue <= 1E3, "#,0",
					        CurrentValue <= 1E6, "#,0, K",
					        CurrentValue <= 1E9, "#,0,, M",
					        CurrentValue <= 1E12, "#,0,,, B"
					    ),
					
					IF(CONTAINSSTRING(FormatString, "%"), FormatString
					,
					
					IF(CONTAINSSTRING(FormatString, "$"),
					    SWITCH (
					        TRUE (),
					        // Special cases to force K and M in the sample report
					        CurrentValue <= 1E3, "$#,0.0",
					        CurrentValue <= 1E6, "$#,0,.0 K",
					        CurrentValue <= 1E9, "$#,0,,.0 M",
					        CurrentValue <= 1E12, "$#,0,,,.0 B"
					    ),
					
					IF(CONTAINSSTRING(FormatString, " kt"),
					    SWITCH (
					        TRUE (),
					        // Special cases to force K and M in the sample report
					        CurrentValue <= 1E3, "#,0.0 kt",
					        CurrentValue <= 1E6, "#,0,.0 K kt",
					        CurrentValue <= 1E9, "#,0,,.0 M kt",
					        CurrentValue <= 1E12, "#,0,,,.0 B kt"
					    ),
					
					    SWITCH (
					        TRUE (),
					        // Special cases to force K and M in the sample report
					       CurrentValue <= 1E3, "#,0; -#,0" ,
					       CurrentValue<= 1E6, "#,0,.0 K;,-#,0,.0 K",
					       CurrentValue <= 1E9, "#,0,,.0 M; -#,0,,.0 M",
					       CurrentValue <= 1E12, "#,0,,,.#0 B; -#,0,,,.#0 B"
					    )))))))
					```

